from common.datatypes import Int8

GAME_REQUEST_AUTH_LOGIN = Int8(8)
GAME_REQUEST_CHARACTER_CREATE = Int8(11)
GAME_REQUEST_CHARACTER_DELETE = None
GAME_REQUEST_NEW_CHARACTER = Int8(14)
GAME_REQUEST_PROTOCOL_VERSION = Int8(0)


GAME_AUTH_LOGIN_FAIL_BAD = Int8(1)
