version: "3"

services:
  mongo:
    image: mongo
  common:
    image: l2py_common
    build:
      context: ./common
  data:
    build:
      context: ./data
    restart: always
    environment:
      MONGO_URI: mongo

  login:
    build:
      context: ./login
    restart: always
    environment:
      DATA_SERVER_HOST: data
    ports:
      - "2106:2106"

  game:
    build:
      context: ./game
    restart: always
    environment:
      DATA_SERVER_HOST: data
      LOGIN_SERVER_API_HOST: login
    ports:
      - "7777:7777"
