version: "3"

services:
  mongo:
    image: mongo
  data:
    build:
      dockerfile: ./data/Dockerfile
      context: .
    environment:
      MONGO_URI: mongo

  login:
    build:
      dockerfile: ./login/Dockerfile
      context: .
    environment:
      DATA_SERVER_HOST: data
    ports:
      - "2106:2106"

  game:
    build:
      dockerfile: ./game/Dockerfile
      context: .
    environment:
      DATA_SERVER_HOST: data
      LOGIN_SERVER_API_HOST: login
    ports:
      - "7777:7777"
