version: "3"

services:
  mongo:
    image: mongo

  login:
    build:
      context: src/login
    restart: always
    env_file:
      - .env
    ports:
      - 2106:2106

  game:
    build:
      context: src/game
    restart: always
    env_file:
      - .env
    ports:
      - 7777:7777
