GAME_REQUEST_AUTH_LOGIN = Int8(8)
GAME_REQUEST_CHARACTER_CREATE = Int8(11)
GAME_REQUEST_CHARACTER_DELETE = Int8(12)
GAME_REQUEST_NEW_CHARACTER = Int8(14)
GAME_REQUEST_PROTOCOL_VERSION = Int8(0)
GAME_REQUEST_CHARACTER_RESTORE = Int8(98)
GAME_REQUEST_CHARACTER_SELECTED = Int8(13)
GAME_REQUEST_ENTER_WORLD = Int8(3)
GAME_REQUEST_MOVE_BACK_TO_LOCATION = Int8(1)
GAME_REQUEST_RESTART = Int8(70)
GAME_REQUEST_SAY2 = Int8(56)
GAME_REQUEST_ACTION = Int8(4)
GAME_REQUEST_TARGET_CANCEL = Int8(55)
GAME_REQUEST_ATTACK = Int8(10)
GAME_REQUEST_OPEN_MINIMAP = Int8(205)
GAME_REQUEST_ACTION_USE = Int8(69)
GAME_REQUEST_SOCIAL_ACTION = Int8(27)

GAME_AUTH_LOGIN_FAIL_DEFAULT = Int8(0)
GAME_AUTH_LOGIN_FAIL_SYSTEM_ERROR = Int8(1)
GAME_AUTH_LOGIN_FAIL_PASSWORD_DOESNT_MATCH = Int8(2)
GAME_AUTH_LOGIN_FAIL_TRY_LATER = Int8(4)
GAME_AUTH_LOGIN_FAIL_CONTACT_SUPPORT = Int8(5)
GAME_AUTH_LOGIN_FAIL_ALREADY_IN_USE = Int8(7)

GAME_CHAR_CREATE_FAIL_DEFAULT = Int32(0)
GAME_CHAR_CREATE_FAIL_TOO_MANY = Int32(1)
GAME_CHAR_CREATE_FAIL_ALREADY_EXIST = Int32(2)
GAME_CHAR_CREATE_FAIL_ENCODING_ERROR = Int32(3)


BODY_PART_HEAD = "head"
BODY_PART_HEAD_ALL = "dhead"
BODY_PART_FACE = "face"
BODY_PART_HAIR = "hair"
BODY_PART_DHAIR = "dhair"
BODY_PART_LEFT_EAR = "lear"
BODY_PART_RIGHT_EAR = "rear"
BODY_PART_NECK = "neck"
BODY_PART_LEFT_FINGER = "lfinger"
BODY_PART_RIGHT_FINGER = "rfinger"
BODY_PART_GLOVES = "gloves"
BODY_PART_CHEST = "chest"
BODY_PART_LEGS = "legs"
BODY_PART_FEET = "feet"
BODY_PART_FULL_ARMOR = "fullarmor"
BODY_PART_UNDERWEAR = "underwear"
BODY_PART_WOLF = "wolf"
BODY_PART_HATCHLING = "hatchling"
BODY_PART_STRIDER = "strider"
BODY_PART_BABY_PET = "babypet"

ALL_BODY_PARTS = [
    BODY_PART_HEAD,
    BODY_PART_HEAD_ALL,
    BODY_PART_FACE,
    BODY_PART_HAIR,
    BODY_PART_DHAIR,
    BODY_PART_LEFT_EAR,
    BODY_PART_RIGHT_EAR,
    BODY_PART_NECK,
    BODY_PART_LEFT_FINGER,
    BODY_PART_RIGHT_FINGER,
    BODY_PART_GLOVES,
    BODY_PART_CHEST,
    BODY_PART_LEGS,
    BODY_PART_FEET,
    BODY_PART_FULL_ARMOR,
    BODY_PART_UNDERWEAR,
    BODY_PART_WOLF,
    BODY_PART_HATCHLING,
    BODY_PART_STRIDER,
    BODY_PART_BABY_PET,
]


ARMOR_TYPE_LIGHT = "light"
ARMOR_TYPE_HEAVY = "heavy"


ACTION_TARGET = Int32(0)
ACTION_TARGET_SHIFT = Int32(1)
ACTION_SIT = Int32(0)
ACTION_RUN = Int32(1)
ACTION_FAKE_DEATH_START = Int32(2)
ACTION_FAKE_DEATH_STOP = Int32(3)
ACTION_COMMON_CRAFT = Int32(51)

SOCIAL_ACTION_HELLO = Int32(2)
SOCIAL_ACTION_VICTORY = Int32(3)
SOCIAL_ACTION_ADVANCE = Int32(4)
SOCIAL_ACTION_NO = Int32(6)
SOCIAL_ACTION_YES = Int32(6)
SOCIAL_ACTION_BOW = Int32(7)
SOCIAL_ACTION_UNAWARE = Int32(8)
SOCIAL_ACTION_WAITING = Int32(9)
SOCIAL_ACTION_LAUGH = Int32(10)
SOCIAL_ACTION_APPLAUD = Int32(11)
SOCIAL_ACTION_DANCE = Int32(12)
SOCIAL_ACTION_SORROW = Int32(13)
PUBLIC_SOCIAL_ACTIONS = [
    SOCIAL_ACTION_HELLO,
    SOCIAL_ACTION_VICTORY,
    SOCIAL_ACTION_ADVANCE,
    SOCIAL_ACTION_NO,
    SOCIAL_ACTION_YES,
    SOCIAL_ACTION_BOW,
    SOCIAL_ACTION_UNAWARE,
    SOCIAL_ACTION_WAITING,
    SOCIAL_ACTION_LAUGH,
    SOCIAL_ACTION_APPLAUD,
    SOCIAL_ACTION_DANCE,
    SOCIAL_ACTION_SORROW,
]

SEVEN_SIGNS_PERIOD_COMPETITION_RECRUITING = Int32(0)
SEVEN_SIGNS_PERIOD_COMPETITION = Int32(1)
SEVEN_SIGNS_PERIOD_COMPETITION_RESULTS = Int32(2)
SEVEN_SIGNS_PERIOD_SEAL_VALIDATION = Int32(3)

WAIT_TYPE_SITTING = Int32(0)
WAIT_TYPE_STANDING = Int32(1)
WAIT_TYPE_START_FAKE_DEATH = Int32(2)
WAIT_TYPE_STOP_FAKE_DEATH = Int32(3)
