import cython

GAME_REQUEST_AUTH_LOGIN = cython.char(8)
GAME_REQUEST_CHARACTER_CREATE = cython.char(11)
GAME_REQUEST_CHARACTER_DELETE = cython.char(12)
GAME_REQUEST_NEW_CHARACTER = cython.char(14)
GAME_REQUEST_PROTOCOL_VERSION = cython.char(0)
GAME_REQUEST_CHARACTER_RESTORE = cython.char(98)
GAME_REQUEST_CHARACTER_SELECTED = cython.char(13)
GAME_REQUEST_ENTER_WORLD = cython.char(3)
GAME_REQUEST_MOVE_BACK_TO_LOCATION = cython.char(1)
GAME_REQUEST_RESTART = cython.char(70)
GAME_REQUEST_SAY2 = cython.char(56)
GAME_REQUEST_ACTION = cython.char(4)
GAME_REQUEST_TARGET_CANCEL = cython.char(55)
GAME_REQUEST_ATTACK = cython.char(10)
GAME_REQUEST_OPEN_MINIMAP = cython.char(205)
GAME_REQUEST_ACTION_USE = cython.char(69)
GAME_REQUEST_SOCIAL_ACTION = cython.char(27)
GAME_REQUEST_VALIDATE_POSITION = cython.char(72)

GAME_AUTH_LOGIN_FAIL_DEFAULT = cython.char(0)
GAME_AUTH_LOGIN_FAIL_SYSTEM_ERROR = cython.char(1)
GAME_AUTH_LOGIN_FAIL_PASSWORD_DOESNT_MATCH = cython.char(2)
GAME_AUTH_LOGIN_FAIL_TRY_LATER = cython.char(4)
GAME_AUTH_LOGIN_FAIL_CONTACT_SUPPORT = cython.char(5)
GAME_AUTH_LOGIN_FAIL_ALREADY_IN_USE = cython.char(7)

GAME_CHAR_CREATE_FAIL_DEFAULT = cython.long(0)
GAME_CHAR_CREATE_FAIL_TOO_MANY = cython.long(1)
GAME_CHAR_CREATE_FAIL_ALREADY_EXIST = cython.long(2)
GAME_CHAR_CREATE_FAIL_ENCODING_ERROR = cython.long(3)


BODY_PART_HEAD = "head"
BODY_PART_HEAD_ALL = "dhead"
BODY_PART_FACE = "face"
BODY_PART_HAIR = "hair"
BODY_PART_DHAIR = "dhair"
BODY_PART_LEFT_EAR = "lear"
BODY_PART_RIGHT_EAR = "rear"
BODY_PART_NECK = "neck"
BODY_PART_LEFT_FINGER = "lfinger"
BODY_PART_RIGHT_FINGER = "rfinger"
BODY_PART_GLOVES = "gloves"
BODY_PART_CHEST = "chest"
BODY_PART_LEGS = "legs"
BODY_PART_FEET = "feet"
BODY_PART_FULL_ARMOR = "fullarmor"
BODY_PART_UNDERWEAR = "underwear"
BODY_PART_WOLF = "wolf"
BODY_PART_HATCHLING = "hatchling"
BODY_PART_STRIDER = "strider"
BODY_PART_BABY_PET = "babypet"

ALL_BODY_PARTS = [
    BODY_PART_HEAD,
    BODY_PART_HEAD_ALL,
    BODY_PART_FACE,
    BODY_PART_HAIR,
    BODY_PART_DHAIR,
    BODY_PART_LEFT_EAR,
    BODY_PART_RIGHT_EAR,
    BODY_PART_NECK,
    BODY_PART_LEFT_FINGER,
    BODY_PART_RIGHT_FINGER,
    BODY_PART_GLOVES,
    BODY_PART_CHEST,
    BODY_PART_LEGS,
    BODY_PART_FEET,
    BODY_PART_FULL_ARMOR,
    BODY_PART_UNDERWEAR,
    BODY_PART_WOLF,
    BODY_PART_HATCHLING,
    BODY_PART_STRIDER,
    BODY_PART_BABY_PET,
]


ARMOR_TYPE_LIGHT = "light"
ARMOR_TYPE_HEAVY = "heavy"


ACTION_TARGET = cython.long(0)
ACTION_TARGET_SHIFT = cython.long(1)
ACTION_SIT = cython.long(0)
ACTION_RUN = cython.long(1)
ACTION_FAKE_DEATH_START = cython.long(2)
ACTION_FAKE_DEATH_STOP = cython.long(3)
ACTION_COMMON_CRAFT = cython.long(51)

SOCIAL_ACTION_HELLO = cython.long(2)
SOCIAL_ACTION_VICTORY = cython.long(3)
SOCIAL_ACTION_ADVANCE = cython.long(4)
SOCIAL_ACTION_NO = cython.long(5)
SOCIAL_ACTION_YES = cython.long(6)
SOCIAL_ACTION_BOW = cython.long(7)
SOCIAL_ACTION_UNAWARE = cython.long(8)
SOCIAL_ACTION_WAITING = cython.long(9)
SOCIAL_ACTION_LAUGH = cython.long(10)
SOCIAL_ACTION_APPLAUD = cython.long(11)
SOCIAL_ACTION_DANCE = cython.long(12)
SOCIAL_ACTION_SORROW = cython.long(13)
PUBLIC_SOCIAL_ACTIONS = [
    SOCIAL_ACTION_HELLO,
    SOCIAL_ACTION_VICTORY,
    SOCIAL_ACTION_ADVANCE,
    SOCIAL_ACTION_NO,
    SOCIAL_ACTION_YES,
    SOCIAL_ACTION_BOW,
    SOCIAL_ACTION_UNAWARE,
    SOCIAL_ACTION_WAITING,
    SOCIAL_ACTION_LAUGH,
    SOCIAL_ACTION_APPLAUD,
    SOCIAL_ACTION_DANCE,
    SOCIAL_ACTION_SORROW,
]

SEVEN_SIGNS_PERIOD_COMPETITION_RECRUITING = cython.long(0)
SEVEN_SIGNS_PERIOD_COMPETITION = cython.long(1)
SEVEN_SIGNS_PERIOD_COMPETITION_RESULTS = cython.long(2)
SEVEN_SIGNS_PERIOD_SEAL_VALIDATION = cython.long(3)

WAIT_TYPE_SITTING = cython.long(0)
WAIT_TYPE_STANDING = cython.long(1)
WAIT_TYPE_START_FAKE_DEATH = cython.long(2)
WAIT_TYPE_STOP_FAKE_DEATH = cython.long(3)
