REQUEST_GG_AUTH = 7
REQUEST_SERVER_LIST = 5
REQUEST_AUTH_LOGIN = 0
REQUEST_SERVER_LOGIN = 2

LOGIN_FAIL_SYSTEM_ERROR = 1
LOGIN_FAIL_WRONG_PASSWORD = 2
LOGIN_FAIL_WRONG_LOGIN_OR_PASSWORD = 2
LOGIN_FAIL_ACCESS_DENIED = 4
LOGIN_FAIL_DATABASE_ERROR = 5
LOGIN_FAIL_ACCOUNT_ALREADY_IN_USE = 7
LOGIN_FAIL_ACCOUNT_BANNED = 9
LOGIN_FAIL_MAINTENANCE = 16
LOGIN_FAIL_EXPIRED = 18
LOGIN_FAIL_TIME_IS_UP = 19


PLAY_FAIL_PASSWORD_MISMATCH = 2
PLAY_FAIL_ACCESS_DENIED = 4
PLAY_FAIL_TOO_MANY_USERS = 15
