name: poetry
description: Prepares poetry evnironment
runs:
  using: composite

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3.10 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry config virtualenvs.in-project true

    - name: Check for poetry cache
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Make poetry venv
      shell: bash
      run: |
        poetry install
      if: steps.cache-venv.outputs.cache-hit != 'true'
