name: PR static code check

on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        uses: ./.github/actions/poetry

      - name: Check imports with isort
        shell: bash
        run: |
          poetry run isort -c .

  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        uses: ./.github/actions/poetry

      - name: Check formatting with black
        shell: bash
        run: |
          poetry run black --check .
