name: PR static code check

on: [pull_request_target]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to PR
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.0'

    - name: Install Poetry and dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3.10 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry install
    
    - name: Check formatting with black
      run: |
        poetry run black . --check
        
    - name: Check imports with isort
      run: |
        poetry run isort -c .

####  TODO: Add pylint