name: PR static code check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.0'

    - name: Set up cache for poetry
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3.10 -

    - name: Make poetry venv
      run: |
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry install
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Activate venv
      run: . ./.venv/bin/activate
      
    - name: Check formatting with black
      run: |
        poetry run black . --check
        
    - name: Check imports with isort
      run: |
        poetry run isort -c .

####  TODO: Add pylint